"""add Department

Revision ID: 652858ff539f
Revises: 7c4db38b47db
Create Date: 2024-09-21 06:49:47.321228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652858ff539f'
down_revision = '7c4db38b47db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
